apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: order-api-component
spec:
  workloadType: core.oam.dev/v1alpha1.Server
  containers:
    - name: order-api-container
      image: tomkerkhove/keda-sample-dotnet-api
      env:
        - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
          fromParam: ServiceBus_Queue_Connectionstring
      ports:
        - protocol: TCP
          containerPort: 80
          name: http
  parameters:
    - name: ServiceBus_Queue_Connectionstring
      description: 'Connection string for the Azure Service Bus queue'
      type: string
      required: true